// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Yj_62TSUFWfwZVfXwpDFBm9_grfvG3w',
    appId: '1:282083267628:web:82cd0b7c421bc2d2612d89',
    messagingSenderId: '282083267628',
    projectId: 'project-865b4',
    authDomain: 'project-865b4.firebaseapp.com',
    storageBucket: 'project-865b4.firebasestorage.app',
    measurementId: 'G-NZRF4MN3LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYGcpIFlqXhjufCfRLLqEtqrSNNRytXOM',
    appId: '1:282083267628:android:9f96cc3f0f130473612d89',
    messagingSenderId: '282083267628',
    projectId: 'project-865b4',
    storageBucket: 'project-865b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuy1ydpM3uRVorgmqPjy0KmI6ts2DffH8',
    appId: '1:282083267628:ios:df279b5e12e574d6612d89',
    messagingSenderId: '282083267628',
    projectId: 'project-865b4',
    storageBucket: 'project-865b4.firebasestorage.app',
    iosBundleId: 'com.example.applicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuy1ydpM3uRVorgmqPjy0KmI6ts2DffH8',
    appId: '1:282083267628:ios:df279b5e12e574d6612d89',
    messagingSenderId: '282083267628',
    projectId: 'project-865b4',
    storageBucket: 'project-865b4.firebasestorage.app',
    iosBundleId: 'com.example.applicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Yj_62TSUFWfwZVfXwpDFBm9_grfvG3w',
    appId: '1:282083267628:web:4fa24359c6268a2b612d89',
    messagingSenderId: '282083267628',
    projectId: 'project-865b4',
    authDomain: 'project-865b4.firebaseapp.com',
    storageBucket: 'project-865b4.firebasestorage.app',
    measurementId: 'G-MR1BTCM9KZ',
  );

}